In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder


In [2]:
# Função para realizar one-hot encoding de uma sequência de DNA
def one_hot1(sequence):
    mapping = {'A': [1, 0, 0, 0],
               'C': [0, 1, 0, 0],
               'G': [0, 0, 1, 0],
               'T': [0, 0, 0, 1]}
    
    # Transforma cada base da sequência no vetor correspondente
    return np.array([mapping[base] for base in sequence])

In [3]:
def one_hot2(sequence):
    seq_array = np.array(list(sequence))
    
    le = LabelEncoder()
    oe = OneHotEncoder(sparse_output=False)
    integer_e = le.fit_transform(seq_array)
    integer_e = integer_e.reshape(len(integer_e),1)
    onehot_e = oe.fit_transform(integer_e)
    
    return onehot_e

In [4]:
# Função para ler o CSV e gerar os encodings
def process_csv(file_path, function):
    # Lê o CSV ignorando a primeira linha
    df = pd.read_csv(file_path)    
    
    # Aplica o one-hot encoding nas sequências
    if function == 1:
        encoded_sequences = np.array([one_hot1(seq) for seq in df['sequence']])
    elif function == 2:
        encoded_sequences = np.array([one_hot2(seq) for seq in df['sequence']])
        
    # encoded_df = pd.DataFrame(encoded_sequences)
    labels = df['label']
    # Adiciona a coluna de labels ao DataFrame
    # encoded_df['label'] = labels
    
    return encoded_sequences, labels


In [12]:
# Exemplo de uso
csv_file = 'train.csv'
encoded_sequences, labels = process_csv(csv_file, 1)

In [13]:
type(encoded_sequences[1][1][1])

numpy.int64

In [7]:
print(encoded_sequences)

[[[0 1 0 0]
  [0 0 0 1]
  [0 0 1 0]
  ...
  [0 1 0 0]
  [1 0 0 0]
  [1 0 0 0]]

 [[0 1 0 0]
  [1 0 0 0]
  [0 0 0 1]
  ...
  [0 1 0 0]
  [0 0 0 1]
  [0 0 1 0]]

 [[0 0 0 1]
  [0 0 0 1]
  [0 0 1 0]
  ...
  [0 0 1 0]
  [0 1 0 0]
  [0 0 1 0]]

 ...

 [[0 0 1 0]
  [0 0 1 0]
  [0 1 0 0]
  ...
  [0 0 0 1]
  [0 1 0 0]
  [0 1 0 0]]

 [[0 0 1 0]
  [0 0 0 1]
  [0 0 0 1]
  ...
  [0 1 0 0]
  [1 0 0 0]
  [0 1 0 0]]

 [[0 0 0 1]
  [0 0 1 0]
  [0 0 1 0]
  ...
  [0 0 1 0]
  [0 0 1 0]
  [1 0 0 0]]]
